services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: bash -c "yarn watch"
    ports:
      - "3000:3000"
    tty: true
