FROM mcr.microsoft.com/devcontainers/typescript-node:22

ENV PROJECT_ROOT=/usr/src/app
ENV NODE_ENV=development

WORKDIR $PROJECT_ROOT

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
